services:
  - type: web
    name: watchme-eliminacion-cuenta
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: ZOHO_EMAIL
        sync: false
      - key: ZOHO_PASSWORD
        sync: false
      - key: ZOHO_HOST
        value: smtp.zoho.com
      - key: ZOHO_PORT
        value: 465
      - key: CODIGO_EXPIRACION
        value: 30
      - key: API_KEY
        sync: false
      - key: FIREBASE_TYPE
        value: service_account
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: FIREBASE_UNIVERSE_DOMAIN
        value: googleapis.com
